DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS tags_connection;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS accounts;